keys:
  - &host_pear age1q5yc4luyu7qpqpsm579ug59zuj92m56qqn4gdpw74lcnqepzveuqwl7eh4
  - &host_kiwi age1ajf9dmcukxsya3rxqyput9wfmtnsweq9c8evgp3mx8nn7dkau5kswfcqnf
  - &host_orange age1dpss7e28zr5ss34ajszlw3lmfuzw0rw5rkrcx8gexw44jpha5y8q7c3742
  - &host_strawberry age1aarll6pr2mjq9l3a7mc2lxp6djy0a7xhneemwumcq092dzvtqgxsfyumxm
  - &user_bddvlpr age16aazmlnarycwuk3a9e5sr55e2354sydn9qd5c6edhly9rq9k693s43txeq

creation_rules:
  - path_regex: users/bddvlpr/[^/]+\.yaml$
    key_groups:
      - age:
          - *host_pear
          - *host_kiwi
          - *host_orange
          - *host_strawberry
          - *user_bddvlpr
  - path_regex: systems/pear/[^/]+\.yaml$
    key_groups:
      - age:
          - *host_pear
          - *user_bddvlpr
  - path_regex: systems/kiwi/[^/]+\.yaml$
    key_groups:
      - age:
          - *host_kiwi
          - *user_bddvlpr
  - path_regex: systems/orange/[^/]+\.yaml$
    key_groups:
      - age:
          - *host_orange
          - *user_bddvlpr
  - path_regex: systems/strawberry/[^/]+\.yaml$
    key_groups:
      - age:
          - *host_strawberry
          - *user_bddvlpr
