keys:
  - &host_lychee age18a3mm5xhtem23d2mf3chjv4xxfm48n9xruzjaq42s046hmvqhqgq888s5z
  - &host_mango age14u3vde7hnj66eemqj0maf265yc2k0ashg9w0xajwmcwjflxr6e7sythp80
  - &user_bddvlpr_lychee age14ta3t25lxt2nhlh9umh0kk6h3vzyaxqr0f490fzswcluehmt35yswgu2tj

creation_rules:
  - path_regex: users/bddvlpr/[^/]+\.yaml$
    key_groups:
      - age:
          - *host_lychee
          - *host_mango
          - *user_bddvlpr_lychee
  - path_regex: systems/lychee/[^/]+\.yaml$
    key_groups:
      - age:
          - *host_lychee
          - *user_bddvlpr_lychee
  - path_regex: systems/mango/[^/]+\.yaml$
    key_groups:
      - age:
          - *host_mango
          - *user_bddvlpr_lychee
